# # Default zingo lib lightwalletd conf YAML for regtest mode # #
bind-addr: 127.0.0.1:80
cache-size: 10
log-file: ./dev/stdout/log.log
log-level: 10
zcash-conf-path: ~/.zcash/zcash.conf

# example config for TLS
# tls-cert: cert.pem
# tls-key: key.pem
